classdef adPtychoX_fpm < deep.DifferentiableFunction
    %{
        Automatic differentiation module for Fourier ptychographic microscopy (FPM)
        Supports both CPU and CUDA implementations for forward/backward propagation
        Authors: Shuhe Zhang, Liangcai Cao
        {shuhe-zhang, clc}@tsinghua.edu.cn
    %}
    properties
        cuFFThandle_single;
        cuFFThandle_many;
        Xfwd_buffer = [];
        Xrcd_buffer = [];
    end

    methods
        function self = adPtychoX_fpm(arg)
            arguments
                arg.high_Res = 512;
                arg.low_Res = 128;
                arg.batch_size = 16;
            end
            % Constructor for FPM auto-differentiation module
            % Input: use_CUDA - boolean flag to enable GPU acceleration
            
            output_num = 1; % important!!!

            self@deep.DifferentiableFunction(...
                        output_num,...
                        SaveInputsForBackward = true,...
                        SaveOutputsForBackward = false,...
                        NumMemoryValues = 0);

            [self.cuFFThandle_single, ...
             self.cuFFThandle_many,...
             self.Xfwd_buffer, ...
             self.Xrcd_buffer ...
             ] = init_ptyX_fpm_buffers( ...
                int32(arg.high_Res), ...
                int32(arg.high_Res), ...
                int32(arg.batch_size), ...
                int32(arg.low_Res) ...
            );

        end

        function delete(self)
            if ~isempty(self.cuFFThandle_single)
                delete_ptyX_fpm_buffers( ...
                    self.cuFFThandle_single, ...
                    self.cuFFThandle_many, ...
                    self.Xfwd_buffer, ...
                    self.Xrcd_buffer ...
                );
            end
        end
        % forward function
        function [pred_Y] = forward(self,...
                                           wavefront1, ...
                                           wavefront2, ...
                                           dY_obs, ...
                                           ledIdx, ...
                                           pratio)

            % CUDA implementation: fused kernel operation
            [pred_Y] = fwd_adPtychoX_fpm( ...
                wavefront1,...
                wavefront2,...
                dY_obs,...
                int32(ledIdx),...
                self.cuFFThandle_single,...
                self.cuFFThandle_many, ...
                self.Xfwd_buffer, ...
                self.Xrcd_buffer ...
            );
            pred_Y = pred_Y./ pratio^2;
        end

        % backward function
        function [dldw1,...
                  dldw2,...
                  dldY,...
                  dldled,...
                  dldP] = backward(self,dl_dout,...
                                     ~,...
                                     wavefront1, ...
                                     wavefront2, ...
                                     dY_obs, ...
                                     ledIdx, ...
                                     pratio)

            % Backward pass for gradient computation
            dldY = [];
            dldled = [];
            dldP = [];
            % CUDA implementation: fused backward kernel, requires
            [dldw1,dldw2] = bwd_adPtychoX_fpm( ...
                                                dl_dout * pratio^2,...
                                                wavefront1,...
                                                wavefront2,...
                                                int32(ledIdx),...
                                                self.cuFFThandle_single,...
                                                self.cuFFThandle_many, ...
                                                self.Xfwd_buffer, ...
                                                self.Xrcd_buffer, ...
                                                dY_obs...
                                             );
        
        end
    end
end
