classdef adPtychoX_nearf < deep.DifferentiableFunction

    properties (SetAccess = private)
        mag;
        cuFFThandle_single;
        cuFFThandle_many;
        wave_buffer;
        Xfwd_buffer;
        Xrcd_buffer;
    end

    methods
        function foo = adPtychoX_nearf(arg)
            arguments
                arg.large_image_size = 512;
                arg.batch_size = 16;
                arg.down_sample_ratio = 4;
            end

            output_num = 1; % important!!!
            
            foo@deep.DifferentiableFunction(...
                        output_num,...
                        SaveInputsForBackward = true,...
                        SaveOutputsForBackward = true,...
                        NumMemoryValues = 0);

            foo.mag = (int32(arg.down_sample_ratio));

            

            [foo.cuFFThandle_single, ...
             foo.cuFFThandle_many, ...
             foo.wave_buffer, ...
             foo.Xfwd_buffer, ...
             foo.Xrcd_buffer] = init_ptyX_nearf_buffers(...
                                                        arg.large_image_size, ...
                                                        arg.large_image_size, ...
                                                        arg.batch_size ...
                                                      );
            disp("Init PtychoX buffters.");
        end
        % forward function
        function observe = forward(foo,...
                                   wavefront1, ...
                                   wavefront2, ...
                                   H_d2,...
                                   shiftsPos)

            observe = fwd_adPtychoX_nearf(...
                                          wavefront1, ...
                                          wavefront2, ...
                                          H_d2, ...
                                          shiftsPos, ...
                                          foo.cuFFThandle_single,...
                                          foo.cuFFThandle_many, ...
                                          foo.wave_buffer, ...
                                          foo.Xrcd_buffer, ...
                                          foo.Xfwd_buffer, ...
                                          foo.mag ...
                                         );
        end

        % backward function
        function [dldw1,...
                  dldw2,...
                  dldH2,...
                  dldPos] = backward(foo,dl_dout,...
                                     ~,...
                                     ~, ...
                                     wavefront2, ...
                                     H_d2, ...
                                     shiftsPos,...
                                     observe)
            dldH2 = [];
            dldPos = [];
 
            [dldw1,dldw2] = bwd_adPtychoX_nearf(...
                                                dl_dout, ...
                                                observe, ...
                                                wavefront2, ...
                                                H_d2, ...
                                                shiftsPos, ...
                                                foo.cuFFThandle_single,...
                                                foo.cuFFThandle_many, ...
                                                foo.Xfwd_buffer, ...
                                                foo.Xrcd_buffer, ...
                                                foo.mag ...
                                                );

            % dldw1 = conj(dldw1);
            % dldw2 = conj(dldw2);
        end

        function delete(foo)

            delete_ptyX_nearf_buffers(...
                foo.cuFFThandle_single, ...
                foo.cuFFThandle_many, ...
                foo.wave_buffer, ...
                foo.Xfwd_buffer, ...
                foo.Xrcd_buffer ...
            );

            disp("PtychoX buffters have been deleted.");
        end
    end
end
