classdef adPtychoX_coded < deep.DifferentiableFunction
    properties
        enable_cuda = true;
    end

    properties (SetAccess = private)
        cuFFT_singplan = [];
        cuFFT_manyplan = [];
        wavefront1_buffer = [];
        X_forward_buffer = [];
        X_record_buffer = [];
        large_image_size = [];
        small_image_size = [];
        batch_size = [];
        downSam_ratio = [];
    end

    methods
        function self = adPtychoX_coded(arg)
            arguments
                arg.enable_cuda = true;
                arg.large_image_size = [];
                arg.small_image_size = [];
                arg.batch_size = [];
            end

            output_num = 1;

            self@deep.DifferentiableFunction( ...
                output_num, ...
                SaveInputsForBackward  = true, ...
                SaveOutputsForBackward = true, ...
                NumMemoryValues        = 0);

            self.enable_cuda = arg.enable_cuda;

            if self.enable_cuda && ...
               ~isempty(arg.large_image_size) && ...
               ~isempty(arg.small_image_size) && ...
               ~isempty(arg.batch_size)
                self.initBuffers(arg.large_image_size, arg.small_image_size, arg.batch_size);
            end
        end

        function observe = forward(self, wavefront1, wavefront2, H_d1, H_d2, shiftsPos)
            if ~self.enable_cuda
                error('adPtychoX_coded:CpuNotImplemented', ...
                    'CPU fallback is not implemented for adPtychoX_coded. Enable CUDA and initialize buffers first.');
            end

            self.assertCudaBuffersReady();

            observe = fwd_adPtychoX_coded( ...
                wavefront1, ...
                wavefront2, ...
                H_d1, ...
                H_d2, ...
                shiftsPos, ...
                self.cuFFT_singplan, ...
                self.cuFFT_manyplan, ...
                self.wavefront1_buffer, ...
                self.X_record_buffer, ...
                self.X_forward_buffer, ...
                self.downSam_ratio ...
            );
        end

        function [dldw1, dldw2, dldH1, dldH2, dldPos] = backward(self, ...
                                                                 dl_dout, ...
                                                                 ~, ...
                                                                 ~, ...
                                                                 wavefront2, ...
                                                                 H_d1, ...
                                                                 H_d2, ...
                                                                 shiftsPos,...
                                                                 observe)
            dldH1 = [];
            dldH2 = [];
            dldPos = [];

            if ~self.enable_cuda
                error('adPtychoX_coded:CpuNotImplemented', ...
                    'CPU fallback is not implemented for adPtychoX_coded.');
            end

            self.assertCudaBuffersReady();

            [dldw1, dldw2] = bwd_adPtychoX_coded( ...
                dl_dout, ...
                observe, ...
                wavefront2, ...
                H_d1, ...
                H_d2, ...
                shiftsPos, ...
                self.cuFFT_singplan, ...
                self.cuFFT_manyplan, ...
                self.X_forward_buffer, ...
                self.X_record_buffer, ...
                self.downSam_ratio ...
            );
        end

        function initBuffers(self, large_image_size, small_image_size, batch_size)
            if ~self.enable_cuda
                return;
            end

            if isa(large_image_size, 'gpuArray')
                large_image_size = gather(large_image_size);
            end
            if isa(small_image_size, 'gpuArray')
                small_image_size = gather(small_image_size);
            end
            if isa(batch_size, 'gpuArray')
                batch_size = gather(batch_size);
            end

            large_image_size = double(large_image_size);
            small_image_size = double(small_image_size);
            batch_size = double(batch_size);

            if mod(large_image_size, small_image_size) ~= 0
                error('adPtychoX_coded:InvalidDownsampleRatio', ...
                    'large_image_size must be an integer multiple of small_image_size.');
            end

            self.clearBuffers();

            [self.cuFFT_singplan, ...
             self.cuFFT_manyplan, ...
             self.wavefront1_buffer, ...
             self.X_forward_buffer, ...
             self.X_record_buffer] = init_ptyX_coded_buffers( ...
                int32(large_image_size), ...
                int32(small_image_size), ...
                int32(batch_size));

            self.large_image_size = large_image_size;
            self.small_image_size = small_image_size;
            self.batch_size = batch_size;
            self.downSam_ratio = int32(large_image_size / small_image_size);
        end

        function clearBuffers(self)
            if ~isempty(self.cuFFT_singplan)
                delete_ptyX_coded_buffers( ...
                    self.cuFFT_singplan, ...
                    self.cuFFT_manyplan, ...
                    self.wavefront1_buffer, ...
                    self.X_forward_buffer, ...
                    self.X_record_buffer);
            end

            self.cuFFT_singplan = [];
            self.cuFFT_manyplan = [];
            self.wavefront1_buffer = [];
            self.X_forward_buffer = [];
            self.X_record_buffer = [];
            self.large_image_size = [];
            self.small_image_size = [];
            self.batch_size = [];
            self.downSam_ratio = [];
        end

        function delete(self)
            self.clearBuffers();
        end
    end

    methods (Access = private)
        function assertCudaBuffersReady(self)
            if isempty(self.cuFFT_singplan) || ...
               isempty(self.cuFFT_manyplan) || ...
               isempty(self.wavefront1_buffer) || ...
               isempty(self.X_forward_buffer) || ...
               isempty(self.X_record_buffer) || ...
               isempty(self.downSam_ratio)
                error('adPtychoX_coded:BuffersNotInitialized', ...
                    ['CUDA buffers are not initialized. Call initBuffers or construct ', ...
                     'with large_image_size, small_image_size, and batch_size.']);
            end
        end
    end
end
