classdef adPtychoX_coded < deep.DifferentiableFunction
    methods
        function foo = adPtychoX_coded()
            output_num = 1; % important!!!

            foo@deep.DifferentiableFunction(...
                        output_num,...
                        SaveInputsForBackward = true,...
                        SaveOutputsForBackward = true,...
                        NumMemoryValues = 2);

        end
        % forward function
        function [observe,memo1,memo2] = forward(~,...
                                           wavefront1, ...
                                           wavefront2, ...
                                           H_d1, ...
                                           H_d2, ...
                                           shiftsPos)

            % shift_pox = [pos(:,1)';pos(:,2)'];
            [memo1, ...
             memo2, ...
             observe] = adPtychoX_coded_Fwd(...
                                            wavefront1, ...
                                            wavefront2, ...
                                            H_d1, ...
                                            H_d2, ...
                                            shiftsPos ...
                                           );
        end

        % backward function
        function [dldw1,...
                  dldw2,...
                  dldH1,...
                  dldH2,...
                  dldPos] = backward(~,dl_dout,...
                                     ~,...
                                     wavefront1, ...
                                     wavefront2, ...
                                     H_d1, ...
                                     H_d2, ...
                                     shiftsPos,...
                                     observe,...
                                     memo1,memo2)

   

            dldH1 = [];
            dldH2 = [];
            dldPos = [];
      
            [dldw1,dldw2] = adPtychoX_coded_Bwd(...
                                                dl_dout, ...
                                                observe, ...
                                                memo2, ...
                                                wavefront2, ...
                                                memo1, ...
                                                H_d1, ...
                                                H_d2, ...
                                                shiftsPos ...
                                               );

        end
    end
end