classdef adPtycho < deep.DifferentiableFunction
    properties
        enable_cuda = true;
    end

    methods
        function self = adPtycho(enable_cuda)
            output_num = 1; % important!!!

            self@deep.DifferentiableFunction(...
                        output_num,...
                        SaveInputsForBackward = true,...
                        SaveOutputsForBackward = false,...
                        NumMemoryValues = 3);

            self.enable_cuda = enable_cuda;

        end
        % forward function
        function [observe,memo1,memo2,cuffthandle] = forward(self,...
                                           wavefront1, ...
                                           wavefront2, ...
                                           pos)
            
            if self.enable_cuda
                % shift_pox = [pos(:,1)';pos(:,2)'];
                [memo1, ...
                 memo2, ...
                 observe, cuffthandle] = cuPtycho_Fwd(...
                                                        wavefront1, ...
                                                        wavefront2, ...
                                                        int32(pos)...
                                                     );
            else
                cuffthandle = [];
                memo1 = gpuArray.zeros(size(wavefront2,1),...
                                     size(wavefront2,2),...
                                     size(pos,2),'single');

                for con = 1:size(pos,2)
                    memo1(:,:,con) = wavefront1(pos(2,con):pos(2,con)+size(wavefront2,1)-1,...
                                                pos(1,con):pos(1,con)+size(wavefront2,2)-1);

                end
                memo2 = memo1 .* wavefront2;
                memo2 = fftshift(fftshift(fft2(memo2),1),2); 
                observe = abs(memo2);
            end
        end

        % backward function
        function [dldw1,...
                  dldw2,...
                  dldps] = backward(self,dl_dout,...
                                     ~,...
                                     wavefront1, ...
                                     wavefront2, ...
                                     pos,...
                                     memo1,memo2,cuffthandle)

            dldps = [];
            
            if self.enable_cuda
                [dldw1,dldw2] = cuPtycho_Bwd(...
                                                dl_dout, ...
                                                wavefront1, ...
                                                wavefront2, ...
                                                int32(pos), ...
                                                memo2, ...
                                                memo1, ...
                                                cuffthandle ...
                                            ); 
            else
                x = dl_dout .* sign(memo2);
                x = ifft2(ifftshift(ifftshift(x,1),2));

                dldw2 = x .* conj(memo1);
                dldw2 = sum(dldw2,3);

                dldw1 = 0 * wavefront1;

                for con = 1:size(pos,2)
                    dldw1(pos(2,con):pos(2,con)+size(wavefront2,1)-1,...
                          pos(1,con):pos(1,con)+size(wavefront2,2)-1) = ...
                    dldw1(pos(2,con):pos(2,con)+size(wavefront2,1)-1,...
                          pos(1,con):pos(1,con)+size(wavefront2,2)-1) + ...
                          x(:,:,con) .* conj(wavefront2);

                end

                dldw2 = conj(dldw2);
                dldw1 = conj(dldw1);
                
            end
        end
    end
end